"""Stable public exports for the coding-agent core layer."""

from __future__ import annotations

from .agent_session import AgentSession, AgentSessionOptions
from .auth import FileAuthStorage, MemoryAuthStorage
from .extensions import FileExtensionRunner
from .model_registry import FileModelRegistry
from .providers import ProviderBootstrapResult, ProviderRegistryConfig, ProviderRoute, ensure_provider_registered
from .resource_loader import FileResourceLoader
from .rpc import RpcClient
from .schemas import available_schemas, load_schema, load_schema_registry, schema_path, validate_schema
from .settings import FileSettingsManager
from .tools import create_default_tools
from .types import (
    AuthStorage,
    AuthStorageData,
    BranchSummary,
    CompactionInput,
    CompactionPlan,
    CompactionResult,
    CompactionStrategy,
    CredentialRecord,
    ExtensionContext,
    ExtensionDefinition,
    ExtensionEvent,
    ExtensionHookType,
    ExtensionRuntime,
    ExtensionRunner,
    ExtensionType,
    LoadExtensionsResult,
    ModelRegistry,
    ModelRegistryEntry,
    ModelRegistryResult,
    ModelSelectionMode,
    ReadonlySessionManager,
    ResourceCollision,
    ResourceDiagnostic,
    ResourceGroup,
    ResourceItem,
    ResourceKind,
    ResourceLoadResult,
    ResourceLoader,
    RpcCommand,
    RpcEnvelope,
    RpcResponse,
    RpcTransport,
    SessionBranchSummaryEntry,
    SessionCompactionEntry,
    SessionContext,
    SessionCustomEntry,
    SessionCustomMessageEntry,
    SessionEntry,
    SessionEntryKind,
    SessionHeader,
    SessionInfo,
    SessionInfoEntry,
    SessionLabelEntry,
    SessionManager,
    SessionMessageEntry,
    SessionStats,
    SessionTreeNode,
    Settings,
    SettingsLoadResult,
    SettingsManager,
    SettingsScope,
    SettingsStorage,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolDefinition,
    ToolExecutionContext,
    ToolKind,
    ToolRegistry,
    ToolResultMessage,
    ToolRunner,
    UserMessage,
)

__all__ = [
    "AgentSession",
    "AgentSessionOptions",
    "AuthStorage",
    "AuthStorageData",
    "BranchSummary",
    "CompactionInput",
    "CompactionPlan",
    "CompactionResult",
    "CompactionStrategy",
    "CredentialRecord",
    "ExtensionContext",
    "ExtensionDefinition",
    "ExtensionEvent",
    "ExtensionHookType",
    "ExtensionRuntime",
    "ExtensionRunner",
    "ExtensionType",
    "FileAuthStorage",
    "FileExtensionRunner",
    "FileModelRegistry",
    "FileResourceLoader",
    "FileSettingsManager",
    "LoadExtensionsResult",
    "MemoryAuthStorage",
    "ModelRegistry",
    "ModelRegistryEntry",
    "ModelRegistryResult",
    "ModelSelectionMode",
    "ProviderBootstrapResult",
    "ProviderRegistryConfig",
    "ProviderRoute",
    "ReadonlySessionManager",
    "ResourceCollision",
    "ResourceDiagnostic",
    "ResourceGroup",
    "ResourceItem",
    "ResourceKind",
    "ResourceLoadResult",
    "ResourceLoader",
    "RpcClient",
    "RpcCommand",
    "RpcEnvelope",
    "RpcResponse",
    "RpcTransport",
    "SessionBranchSummaryEntry",
    "SessionCompactionEntry",
    "SessionContext",
    "SessionCustomEntry",
    "SessionCustomMessageEntry",
    "SessionEntry",
    "SessionEntryKind",
    "SessionHeader",
    "SessionInfo",
    "SessionInfoEntry",
    "SessionLabelEntry",
    "SessionManager",
    "SessionMessageEntry",
    "SessionStats",
    "SessionTreeNode",
    "Settings",
    "SettingsLoadResult",
    "SettingsManager",
    "SettingsScope",
    "SettingsStorage",
    "TextContent",
    "ThinkingContent",
    "ToolCall",
    "ToolDefinition",
    "ToolExecutionContext",
    "ToolKind",
    "ToolRegistry",
    "ToolResultMessage",
    "ToolRunner",
    "UserMessage",
    "create_default_tools",
    "ensure_provider_registered",
    "available_schemas",
    "load_schema",
    "load_schema_registry",
    "schema_path",
    "validate_schema",
]
