"""LLM protocol layer for the Python rewrite."""

from .auth import ApiKeySource, EnvironmentApiKeySource, OAuthCredential, OAuthProvider
from .events import (
    AssistantMessageEvent,
    StreamDoneEvent,
    StreamErrorEvent,
    StreamStartEvent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
)
from .models import (
    AssistantMessage,
    ContentBlock,
    CacheRetention,
    Context,
    ImageContent,
    JsonValue,
    Message,
    Model,
    OpenAICompletionsCompat,
    OpenAIResponsesCompat,
    OpenRouterRouting,
    ProviderRef,
    SimpleStreamOptions,
    StreamOptions,
    StopReason,
    TextContent,
    ThinkingContent,
    ThinkingLevel,
    Tool,
    ToolCall,
    ToolResultMessage,
    Transport,
    Usage,
    UserMessage,
)
from .providers import AzureOpenAIResponsesOptions, AzureOpenAIResponsesProvider, BedrockOptions, BedrockProvider, HttpxProviderClient, MistralProvider
from .registry import ApiRegistry, Provider, ProviderRegistry, get_provider, register_provider
from .stream import AssistantMessageStream, complete, stream

__all__ = [
    "ApiKeySource",
    "ApiRegistry",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageStream",
    "ContentBlock",
    "CacheRetention",
    "Context",
    "EnvironmentApiKeySource",
    "ImageContent",
    "JsonValue",
    "Message",
    "Model",
    "OAuthCredential",
    "OAuthProvider",
    "OpenAICompletionsCompat",
    "OpenAIResponsesCompat",
    "OpenRouterRouting",
    "Provider",
    "ProviderRegistry",
    "ProviderRef",
    "AzureOpenAIResponsesOptions",
    "AzureOpenAIResponsesProvider",
    "BedrockOptions",
    "BedrockProvider",
    "MistralProvider",
    "HttpxProviderClient",
    "SimpleStreamOptions",
    "StreamDoneEvent",
    "StreamErrorEvent",
    "StreamOptions",
    "StreamStartEvent",
    "StopReason",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingLevel",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultMessage",
    "Transport",
    "Usage",
    "UserMessage",
    "complete",
    "get_provider",
    "register_provider",
    "stream",
]
